services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    environment:
      - DO_AUTH_TOKEN_FILE=/run/secrets/do_token
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=digitalocean"
      - "--certificatesresolvers.le.acme.email=your-ekpoepol@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      # Optional: custom resolvers to speed up DNS propagation checks
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.do_token:/run/secrets/do_token:ro
      - ~/acme.json:/acme.json
    networks:
      - traefik

networks:
  traefik:
    external: true
