services:
  db-setup:
    image: postgres:17
    entrypoint: /bin/sh
    command:
      - -c
      - |
        export PGPASSWORD=$$(cat /run/secrets/pg_root_pass)
        # Create user if missing
        psql -h db -U pgadmin -tc "SELECT 1 FROM pg_roles WHERE rolname = 'authentik'" | grep -q 1 || \
        psql -h db -U pgadmin -c "CREATE USER authentik WITH PASSWORD '$$(cat /run/secrets/pg_authentik_pass)';"
        # Create DB if missing
        psql -h db -U pgadmin -tc "SELECT 1 FROM pg_database WHERE datname = 'authentik'" | grep -q 1 || \
        psql -h db -U pgadmin -c "CREATE DATABASE authentik OWNER authentik;"
    secrets:
      - pg_root_pass
      - pg_authentik_pass
    networks:
      - postgres
    depends_on:
      - db

  # Your Authentik server
  authentik:
    image: ghcr.io/goauthentik/server:2026.2.2
    command: server
    environment:
      AUTHENTIK_POSTGRESQL__HOST: db
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/pg_authentik_pass
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret
    shm_size: 512mb
    depends_on:
      db:
        condition: service_healthy
      traefik:
        condition: service_healthy
      db-setup:
        condition: service_completed_successfully
    networks:
      - postgres
      - traefik
    secrets:
      - pg_authentik_pass
      - authentik_secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`auth.tisasillyplace.com`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=le"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"


  worker:
    image: ghcr.io/goauthentik/server:2026.2.2
    command: worker
    user: root
    environment:
      AUTHENTIK_POSTGRESQL__HOST: db
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/pg_authentik_pass
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret
    shm_size: 512mb
    depends_on:
      db:
        condition: service_healthy
      db-setup:
        condition: service_completed_successfully
    networks:
      - postgres
    secrets:
      - pg_authentik_pass
      - authentik_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  postgres:
    external: true
  traefik:
    external: true

secrets:
  pg_root_pass:
    file: ~/.secrets/postgres_root
  pg_authentik_pass:
    file: ~/.secrets/postgres_authentik
  authentik_secret:
    file: ~/.secrets/authentik_secret
