services:
  mc-fabric:
    image: itzg/minecraft-server
    container_name: mc-fabric-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MEMORY: "12G"
      DIFFICULTY: "hard"
      MODE: "survival"
      RCON_PASSWORD: "mcrcon"
      VERSION: "LATEST"
      MODRINTH_PROJECTS: |
        lithium
        krypton
        spark
      NETWORK_COMPRESSION_THRESHOLD: "64"
    volumes:
      - /srv/storage/fast/mc-fabric/data:/data
    restart: unless-stopped
  mc-fabric-backups:
    image: itzg/mc-backup
    container_name: mc-fabric-backups
    environment:
      SERVER_HOST: "mc"
      BACKUP_METHOD: "rclone"
      CRON_SCHEDULE: "0 4 * * *"
      RCLONE_REMOTE: "mega"
      RCLONE_DEST_DIR: "BUP/minecraft/world"
      RCON_HOST: "mc"
      RCON_PASSWORD: "mcrcon"
      RCLONE_BWLIMIT: "5M"
      PRUNE_BACKUPS_DAYS: 5
    volumes:
        - /srv/storage/fast/mc-fabric/data:/data:ro
        - /srv/storage/bulk/backups/minecraft/fabric_serv:/backups
        - ~/.config/rclone/rclone.conf:/config/rclone/rclone.conf:ro
    restart: unless-stopped
