services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_USER=pgadmin
    secrets:
      - db_password
    networks:
      - postgres

networks:
  postgres:
    external: true

secrets:
  db_password:
    file: ~/.secrets/postgres_root
